### PR TITLE
Nyup 165 scrollbar

### PR DESCRIPTION
**Pull request by lhenze**
Addressing the vertical scrollbar that appears on the book pages, but shouldn't

### CODE REVIEW

**Comment by da70** [comment]
@lhenze, which of these changes need to be applied to OA Books, too?  Could we make a pull request for that, too?  Until we've consolidated the code I'd like to keep these in lockstep.

**Comment by lhenze** [comment]
@da70 ,  which files did you want to keep in sync?  The CSS between the two projects is fairly different (including the difference that CY uses SASS and OA doesn't.)  
Ok if those differ, but the JS is the same? 
OAbooks does not appear to have the same scrollbar problem.

**Comment by da70** [comment]
@lhenze, yes, at the moment I think we are only concerned about JS being the same.

**Comment by lhenze** [comment]
@da70 see https://github.com/NYULibraries/dlts-open-access-books/pull/4

**Pull request merged**
